name: tests
on:
  push:
    branches: [ main ]
  pull_request_target:
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    # This environment requires approval before running on pull requests so it's safe to access secrets.
    environment: integration-testing
    steps:
      - name: Checkout code pull request
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout code push
        if: github.event_name == 'push'
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
      - name: Run tests 
        run: make integration-tests
        env:
          GCP_ACCOUNT_CREDENTIALS: ${{ secrets.GCP_ACCOUNT_CREDENTIALS }}
          GCP_OAUTH_TOKEN: ${{ secrets.GCP_OAUTH_TOKEN }}
